### ISSUE TITLE
Review of template

### ISSUE THREAD

**Issue by satra** [satra/ProjectManagementTemplate#1]
@KirstieJane - it would be great if you could take a quick look at this template.

TODO:

- [ ] Merge Onboarding guide

**Comment by KirstieJane** [comment]
This looks AWESOME! :sparkles:

I particularly enjoy the fact that you kept my "ermegerd I suck" comments in the abstracts and bios page!

I'm on my phone on a train at the moment. Reply to this and let me know if there are specific points that you think need work. I think some extra documentation to point to the different files would be good. But some of that is in the onboarding repo so it might be easy to bring over.
